print("****** Data Diri Mahasiswa ******")
nim = input("NIM: ")
nama = input("Nama Lengkap: ")
jurusan = input("Jurusan: ")
alamat = input("Alamat: ")

print("Hasil Cetak Data Diatas Adalah:")
print("NIM: " + str(nim))
print("Nama Lengkap: " + str(nama))
print("Jurusan: " + str(jurusan))
print("Alamat: " + str(alamat))